Deploy to kubernetes
ministryofjustice/cloud-platform-support-labelling-webhook pull request #1
Opened 2018-10-03 17:15 UTC by kalbir

2018-10-15 15:46 UTC, jasonBirchall requested changes
Just a small request for change. App deployed following readme and DockerFile looks good.

2018-10-15 15:46 UTC, jasonBirchall commented on README.md
> +correctly when added by non-Webops team members.
Duplicate block of text.

2018-10-16 09:29 UTC, kalbir commented
@jasonBirchall Made that change you requested 👍

2018-10-16 10:06 UTC, jasonBirchall approved these changes

2018-10-16 10:10 UTC, merged